SELECT * INTO [ELMA_BACKUP]..[2023_06_30_ELMA_TABLE_APG_Locality]  FROM [ELMA_DB].[dbo].[ELMA_TABLE_APG_Locality]
SELECT * INTO [ELMA_BACKUP]..[2023_06_30_ELMA_TABLE_Companies@APG_Locality]  FROM [ELMA_DB].[dbo].[ELMA_TABLE_Companies@APG_Locality]
SELECT * INTO [ELMA_BACKUP]..[2023_06_30_ELMA_TABLE_Companies@Contacts]  FROM [ELMA_DB].[dbo].[ELMA_TABLE_Companies@Contacts]
SELECT * INTO [ELMA_BACKUP]..[2023_06_30_ELMA_TABLE_companies@RecordTypeId]  FROM [ELMA_DB].[dbo].[ELMA_TABLE_companies@RecordTypeId]
SELECT * INTO [ELMA_BACKUP]..[2023_06_30_ELMA_TABLE_contacts@RecordTypeId]  FROM [ELMA_DB].[dbo].[ELMA_TABLE_contacts@RecordTypeId]
SELECT * INTO [ELMA_BACKUP]..[2023_06_30_ELMA_TABLE_RecordType]  FROM [ELMA_DB].[dbo].[ELMA_TABLE_RecordType]
SELECT * INTO [ELMA_BACKUP]..[2023_06_30_ELMA_TABLE_Contacts]  FROM [ELMA_DB].[dbo].[ELMA_TABLE_Contacts]
SELECT * INTO [ELMA_BACKUP]..[2023_06_30_ELMA_TABLE_Companies]  FROM [ELMA_DB].[dbo].[ELMA_TABLE_Companies]
SELECT * INTO [ELMA_BACKUP]..[2023_06_30_ELMA_TABLE_UserDetails]  FROM [ELMA_DB].[dbo].[ELMA_TABLE_UserDetails]
SELECT * INTO [ELMA_BACKUP]..[2023_06_30_ELMA_TABLE_Users]  FROM [ELMA_DB].[dbo].[ELMA_TABLE_Users]
SELECT * INTO [ELMA_BACKUP]..[2023_06_30_ELMA_TABLE_Orgstruct]  FROM [ELMA_DB].[dbo].[ELMA_TABLE_Orgstruct]



----------------

DROP TABLE [ELMA_DB].[dbo].[ELMA_TABLE_Contacts]
DROP TABLE [ELMA_DB].[dbo].[ELMA_TABLE_Companies]


SELECT * INTO [ELMA_DB].[dbo].[ELMA_TABLE_Contacts]  FROM [ELMA_BACKUP]..[2023_06_30_ELMA_TABLE_Contacts]
SELECT * INTO [ELMA_DB].[dbo].[ELMA_TABLE_Companies]  FROM [ELMA_BACKUP]..[2023_06_30_ELMA_TABLE_Companies]

